### ISSUE TITLE
Connection reset by peer when running nitriding example

### ISSUE THREAD

**Issue by curtischong** [brave/nitriding#55]
Hello! I've been trying to run the example and have been receiving this error:

`proxy.go:33: TAP tunnel to EC2 host failed: failed to connect to host: dial vsock vm(3):1024: connect: connection reset by peer.  Restarting.`

Would you happen to have a hunch on what I can look at to fix this? This error occurs on a fresh clone of the repo. Any help would be appreciated!

**Comment by NullHypothesis** [comment]
This sounds like nitriding is unable to talk to the [gvproxy application](https://github.com/containers/gvisor-tap-vsock/tree/main/cmd/gvproxy) on the EC2 host. How did you start gvproxy?

**Comment by curtischong** [comment]
Ahh I just ran `./gvproxy`. Do you have to `-forward-sock` any values? Thank you for the prompt response!

**Comment by NullHypothesis** [comment]
Try this:
```
./gvproxy -listen vsock://:1024 -listen unix:///tmp/network.sock
```
This will teach gvproxy to listen on port 1024 on the VSOCK interface, so nitriding can talk to it. It also creates a Unix domain socket that allows you to configure port forwarding rules like this:

```
curl  --unix-socket /tmp/network.sock http:/unix/services/forwarder/expose -X POST -d '{"local":":443","remote":"192.168.127.2:443"}'
```

Note that 192.168.127.2 is nitriding's hard-coded IP address.

The README really should be more clear about this. I'm going to create a PR for this later today.

**Comment by curtischong** [comment]
Thank you so much!
