### ISSUE TITLE
Fix nitriding's broken versioning

### ISSUE THREAD

**Issue by NullHypothesis** [brave/nitriding#60]
Nitriding's version 1 was a Go package that one had to use in Go code. We then abandoned this development model in favor of a stand-alone executable and started using git tags in version 2.

Unfortunately, I was unaware that Go does things differently. When one transitions to a backwards-incompatible version 2, the code of version 2 is supposed to be in a `v2` directory, and meant to be maintained alongside version 1. In other words, the repository is supposed to contain code for both v1 **and** v2:
https://go.dev/blog/v2-go-modules

How should we fix this mess? A few options come to mind:

- Do what Go wants us to do, i.e., restore nitriding's pre-v2 code and have it live in the root directory, and move nitriding v2 to the v2 subdirectory. I'm not a fan of this because I'm not interested in maintaining v1, which is obsolete.
- Pretend that v2 never happened and simply continue using v1, despite the backwards-incompatible changes. This is a somewhat ugly solution but we can get away with it because we have a single project depending on nitriding.
- Other ideas?

(CC @DJAndries, @rillian, and @mwittie because we shouldn't break third-party projects.)

**Comment by rillian** [comment]
Looks like we could also fork to a nitridingv2 or nitriding-daemon repo and archive this one, to keep the code available as golang tooling expects, but clearly signal v1 is unmaintained?

I'm fine with any of the options, with a preference for pretending v2 never happened if @mwittie is ok with that.

Docs use "go in GOPATH mode" as an example of a tool that needs the `v2` path for compatibility. How common is that?

**Comment by mwittie** [comment]
Our fork of nitriding is still off of v1, so it will not disrupt us if you move away from v2. We are interested though in maintaining the Go package version, since that's how we use nitriding in our builds. Maybe there is an opportunity for v2 to stay v2, and for the version we've been maintaining to become v1?

**Comment by DJAndries** [comment]
Could we have two directories, one for v1 and one for v2?

In the v1 directory, we could have a README that signals that v1 is unmaintained like @rillian suggested.

This suggestion also lgtm:

> Looks like we could also fork to a nitridingv2 or nitriding-daemon repo and archive this one, to keep the code available as golang tooling expects, but clearly signal v1 is unmaintained?

**Comment by NullHypothesis** [comment]
I think the most hassle-free way forward is @rillian's suggestion of creating a new repository and archiving this one. How about we do the following:

1. Create a new repository (I do like nitriding-daemon) that contains this repository's code.
2. Migrate our issues, v2.* tags, etc.
3. Revert this repository's `master` to 9edb2c47fd52754ec506816206491740d9629077, which is the last commit before we merged the tap branch.
4. Revise this repository's README.md, explaining that we no longer maintain the code, and people should instead use nitriding-daemon.
5. Archive this repository.

@mwittie: How does the above sound to you?

**Comment by NullHypothesis** [comment]
> Could we have two directories, one for v1 and one for v2?

That's possible, and even encouraged by the official Go docs but it comes with the expectations that we continue maintaining v1, which I'm not interested in.

**Comment by NullHypothesis** [comment]
Ok, we now have https://github.com/brave/nitriding-daemon. I deleted the v2.* tags from this repository and we made it clear in the security policy and the readme that this repository is now archived. I figured there's no need to delete post-v1.* commits. Deleting the respective tags should suffice.
